export const SET_ACTIVE_MEDIA_ITEM="SET_ACTIVE_MEDIA_ITEM";

export const CACHE_WATCHLIST="CACHE_WATCHLIST";

export const SET_IS_AUTHENTICATED="SET_IS_AUTHENTICATED";
export const SET_AUTH_TOKEN="SET_AUTH_TOKEN";